### ISSUE TITLE
Hi, I cannot figure out ow to use this.

### ISSUE THREAD

**Issue by BadNintendo** [InvesthacK/WebRTC-SFU-React-Typescript#2]
I compiled the source and client seems to be compiled, but cannot find client once completed. Would you mind converting this to JavaScript files like source? Would love to be able to see it then and use it. Discord BadNintendo#2597

**Comment by itsanji** [comment]
Hello. thanks for contacting. 
we afraid that the repo is just for tesing and is ARCHIVED/NO-MORE-MAINTENACE and we can't support you.
but I created other branch that don't use https and easier to set up.
[temp/no_https](https://github.com/InvesthacK/WebRTC-SFU-React-Typescript/tree/temp/no_https)
I also added README in both master and temp/no_https branch.
